schema_version = 1
name = "paimon"
extension_config = "extension_config_vane.cmake"
build_extensions = ["httpfs", "parquet"]
native_test_selection = "test/sql/paimon_scan.test"

[vane]
repository = "AstroVela/vane"
revision = "472df75ab51fd3eac2642f6646545075549e5921"
