schema_version = 1
name = "paimon"
extension_config = "extension_config_vane.cmake"
build_extensions = ["httpfs", "parquet"]
native_test_selection = "test/sql/paimon_scan.test"

[vane]
repository = "AstroVela/vane"
revision = "70fea3800ac8bec49e4b8b0edf95c93706f8b4aa"
